# Review of topics

In [2]:
# setting up some variables to use in our reading/writing loop

input_file = "sample.txt"
output_file = "sales_data.csv"

In [4]:
with open(input_file) as f:
    lines = f.readlines()   # readlines() creates a list output of all the lines as strings

print(lines)

['Ice Cream Shop Daily Sales Report\n', 'Date: July 14 2025\n', 'Location: Sunnyside Scoops\n', '\n', 'Flavor,Scoops Sold,Price Per Scoop,Total Revenue\n', 'Vanilla,42,$2.50,$105.00\n', 'Chocolate,38,$2.50,$95.00\n', 'Strawberry,27,$2.50,$67.50\n', 'Mint Chip,31,$2.75,$85.25\n', 'Rocky Road,19,$2.75,$52.25\n', 'Butter Pecan,14,$2.75,$38.50\n', 'Mango Sorbet,22,$3.00,$66.00\n', 'Cookie Dough,35,$3.00,$105.00\n', '\n', 'Total Scoops Sold: 228\n', 'Total Revenue: $614.50\n', 'Best Seller: Vanilla\n', 'Slowest Seller: Butter Pecan\n', 'Weather was sunny and mild']


In [6]:
with open(output_file, "w") as o:
    for i in lines:
        if "," in i:
            o.write(i)
print("Output complete")

Output complete


#### Adding a lambda:

In [10]:
input_file = "sample.txt"
output_file = "sales_data2.csv"

revenue_per_scoop = lambda scoops, revenue: revenue / scoops   # this lambda is creating a little calculator as revenue_per_scoop

In [11]:
with open(input_file) as f:
    lines = f.readlines()

In [12]:
with open(output_file, "w") as o:
    for i in lines:
        if "," in i:
            parts= i.strip().split(",")
            if parts[0] == 'Flavor':
                o.write(i.strip() + ",Revenue Per Scoop\n")
            else: 
                scoops = int(parts[1])
                revenue = float(parts[3].replace("$", ""))
                rps = revenue_per_scoop(scoops, revenue)      # this is where we're using the lambda function
                o.write(f"{i.strip()},${rps:.2f}\n")

print("Output complete")

Output complete


# Error handling

In [17]:
try:
    first_n = float(input('% to calculate: '))
    answer = first_n / 100
except ValueError:
    print('Invalid input! Must be a number')
else:
    print(answer)
finally:
    print('Run again to try another number')

% to calculate:  78 percent


Invalid input! Must be a number
Run again to try another number


In [14]:
# if we didn't use try:

first_n = float(input('% to calculate (as decimal value): '))
answer = first_n / 100

print(answer)

% to calculate (as decimal value):  40 oe==cent


ValueError: could not convert string to float: '40 oe==cent'

In [16]:
try:
    first_n = float(input('% to calculate: '))
    answer = first_n / 100
except ValueError:
    print('Invalid input! Must be a number')
else:
    print(answer)
finally:
    print('Run again to try another number')

% to calculate:  78


0.78
Run again to try another number


### Using try/except with file handling

In [20]:
input_file = "robot_army.txt"
output_file = "sales_data3.csv"

try:
    with open(input_file) as f:
        lines = f.readlines()

except FileNotFoundError:
    print(f"Error: '{input_file}' not found.")

else:
    with open(output_file, "w") as out:
        for line in lines:
            if "," in line:
                out.write(line)
        print(f"Sales table written to '{output_file}'.")

Error: 'robot_army.txt' not found.


# Intro to NumPy

## Creating and working with arrays

In [21]:
import numpy as np

In [32]:
x = [1, 2, 3, 4, 5]
y = ('a', 'b', 'c')
z = {1, 2, 3, 'a', 'b', 'c'}
zz = [1, 2, 3, 'a', 'b', 'c']

In [25]:
x_arr = np.array(x)
print(x_arr)
print(type(x_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [26]:
print(x)
print(x_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [27]:
y_arr = np.array(y)
print(y_arr)

['a' 'b' 'c']


In [29]:
z_arr = np.array(z)  # using the set of z
print(z_arr)

{1, 2, 3, 'c', 'a', 'b'}


In [34]:
zz_arr = np.array(zz)
print(zz_arr)
print(zz)

['1' '2' '3' 'a' 'b' 'c']
[1, 2, 3, 'a', 'b', 'c']


In [35]:
t = (('a', 'b'), ('c', 'd'))  # tuple containing two tuples

In [37]:
t_arr = np.array(t)   # creates a 2-dimensional array
print(t_arr)

[['a' 'b']
 ['c' 'd']]


In [40]:
# u = (('e', 'f'), ('g'))  # uneven number of values creates an "inhomogenous shape"

In [39]:
u_arr = np.array(u)
print(u_arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [45]:
u2 = ((6, 7), (8, np.nan)) 

In [46]:
u2_arr = np.array(u2)
print(u2_arr)

[[ 6.  7.]
 [ 8. nan]]


In [49]:
m_arr = np.array('m')
print(m_arr)
print(type(m_arr))

m
<class 'numpy.ndarray'>


In [55]:
too_much = np.array([([1,2, 1, 2],[3,4, 3,4]),([5,6, 5, 6],[7,8, 7, 8])])
print(too_much)
print(type(too_much))

[[[1 2 1 2]
  [3 4 3 4]]

 [[5 6 5 6]
  [7 8 7 8]]]
<class 'numpy.ndarray'>


In [56]:
too_much.ndim

3

In [57]:
too_much.size

16

In [58]:
too_much.shape

(2, 2, 4)

In [59]:
print(too_much.T)

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]

 [[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [60]:
print(too_much)

[[[1 2 1 2]
  [3 4 3 4]]

 [[5 6 5 6]
  [7 8 7 8]]]


In [62]:
print(too_much[0][0][0])

1


In [64]:
print(too_much[0][1][1])

4
