# Continuing with NumPy

In [3]:
# list of lists (standard Python list object)

example1 = [[1, 2, 3], ['a','b','c']]

In [2]:
print(example1)

[[1, 2, 3], ['a', 'b', 'c']]


In [4]:
import numpy as np

In [5]:
example_a = np.array(example1)

In [6]:
print(example_a)

[['1' '2' '3']
 ['a' 'b' 'c']]


In [7]:
example_a.dtype

dtype('<U11')

In [8]:
# another Python list example

example2 = [(10,11),(12,13),(14,15)]  # list of tuples, tuples only include integers

example_b = np.array(example2)
print(example_b)
print(example_b.dtype)

[[10 11]
 [12 13]
 [14 15]]
int32


In [9]:
example3 = ((1.0,1.1),(2.0,2.1))  # tuple of tuples using floats

example_c = np.array(example3)
print(example_c)
print(example_c.dtype)

[[1.  1.1]
 [2.  2.1]]
float64


In [10]:
example_d = np.array(example3, dtype='i')

In [11]:
print(example_d)
print(example_d.dtype)

[[1 1]
 [2 2]]
int32


In [12]:
example_e = np.array(example1, dtype='i')  # example1 includes mix of int and string values

ValueError: invalid literal for int() with base 10: 'a'

## Working with arrays in different ways

In [13]:
for i in example_a:
    print(i)

['1' '2' '3']
['a' 'b' 'c']


In [14]:
for i in example_a:
    for i2 in i:
        print(i2)
    

1
2
3
a
b
c


In [17]:
example4 = [(    #totally optional to add line breaks at significant list levels, but can be visually useful
    [1,1],
    [2,2],
    [3,3])
            ,(
    [4,4],
    [5,5,],
    [6,6])]

example_f = np.array(example4)
print(example_f)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [21]:
for i in example_f:    # peeling down the 3 dimensions of our 3D array
    #print('outer dimension')
    for i2 in i:
        #print('next dimension')
        for blueberry in i2:
            #print('innermost dimension')
            print(blueberry)

1
1
2
2
3
3
4
4
5
5
6
6


In [23]:
# Concatenating arrays

arr_a = np.array([1, 2, 3]) 
arr_b = np.array([4, 5, 6]) 
arr_c = np.concatenate((arr_a, arr_b))   # just using concatenate by itself, 1D arrays are added together in a line
print(arr_c)

[1 2 3 4 5 6]


In [27]:
# starting with the same 1D arrays, let's stack them on top of each other
arr_stacked = np.stack((arr_a, arr_b))   # stack creates a new output out of the dimensions that were stacked together

print(arr_stacked)

[[1 2 3]
 [4 5 6]]


In [38]:
# concatenate and stack also work with n-dimensional arrays

arr_d = np.array([[1, 2, 1], [3, 4, 3]])   #starting arrays are 2D
arr_e = np.array([[5, 6, 5], [7, 8, 7]]) 

arr_f = np.concatenate((arr_d, arr_e))   # result in a 2D array cocatenated on the outer dimension if no axis is specified
print(arr_f)

[[1 2 1]
 [3 4 3]
 [5 6 5]
 [7 8 7]]


In [39]:
arr_g = np.concatenate((arr_d,arr_e), axis = 1)    # still a 2D array but concatenated on the inner dimension
print(arr_g)

[[1 2 1 5 6 5]
 [3 4 3 7 8 7]]


In [40]:
arr_stacked2 = np.stack((arr_d, arr_e))  # starting again with input arrays that are 2D arrays
print(arr_stacked2)

[[[1 2 1]
  [3 4 3]]

 [[5 6 5]
  [7 8 7]]]


In [42]:
arr_stacked3 = np.stack((arr_a, arr_b), axis = 1)
print(arr_stacked3)

[[1 4]
 [2 5]
 [3 6]]


Takeaway: when concatenating, you are not adding dimensions; you're just stringing together values in the existing dimensions. But when using stack(), you are adding a new dimension

In [44]:
# additional example in response to question: what should you take into account when deciding if you should stack or concatenate?

# You might use concatenate with:
exam_scores = [.78, .89, .92, .82, .99]
exam_scores_makeup = [.90, .85]

# Then if you're adding a second grade to the gradebook, you might stack the above result with:
project_scores = [.88, .91, .97, .85, .96, .89, .87]

In [48]:
exam_all = np.concatenate((np.array(exam_scores), np.array(exam_scores_makeup)))
print(exam_all)

[0.78 0.89 0.92 0.82 0.99 0.9  0.85]


In [49]:
gradebook = np.stack((exam_all, np.array(project_scores)))
print(gradebook)

[[0.78 0.89 0.92 0.82 0.99 0.9  0.85]
 [0.88 0.91 0.97 0.85 0.96 0.89 0.87]]
