In [4]:
# example of creating and array with tuples
import numpy as np

x = np.array([(11, 12, 13), (14, 15, 16)])
print(x)

[[11 12 13]
 [14 15 16]]


## Splitting arrays

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.ndim

1

In [9]:
print(np.array_split(arr, 2))

[array([1, 2, 3]), array([4, 5, 6])]


In [10]:
print(np.array_split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
print(np.array_split(arr, 4))

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [12]:
# split helper functions: hsplit(), vsplit(), dsplit()

print(np.hsplit(arr, 2))

[array([1, 2, 3]), array([4, 5, 6])]


In [14]:
# print(np.hsplit(arr, 4))
# this will throw a ValueError because hsplit requires array to be divided equally

## Using where()

In [15]:
arr

array([1, 2, 3, 4, 5, 6])

In [17]:
print(np.where(arr >= 3))  # where requires a condition (using <, >, ==, etc.)

(array([2, 3, 4, 5], dtype=int64),)


In [20]:
print(np.where(arr % 3 == 0, arr, np.nan)) 
# first argument is the condition
# second argument is what to return if condition IS met
# third argument is what to return if condition IS NOT met

# this pattern of condition is often used to identify even numbers (variable_name % 2 == 0)

[nan nan  3. nan nan  6.]


## Sorting arrays

In [21]:
# using randint() to create a randomized array of integers

sales_figures = np.random.randint(100, size = (3, 4, 5))

print(sales_figures)

[[[ 7 86 35 52 58]
  [16 77 13  5 61]
  [57 90 79 73 72]
  [37 42 40 83 75]]

 [[40 30 76 99 39]
  [82 34 30  9 16]
  [30 56 62 40 48]
  [36 16 38 38 38]]

 [[ 9 33 72 31 87]
  [58 18 45 24 26]
  [99 17 78 39 95]
  [98 32 53 67 39]]]


In [27]:
# practice with sort()

print(np.sort(sales_figures, axis = 0))

[[[ 7 30 35 31 39]
  [16 18 13  5 16]
  [30 17 62 39 48]
  [36 16 38 38 38]]

 [[ 9 33 72 52 58]
  [58 34 30  9 26]
  [57 56 78 40 72]
  [37 32 40 67 39]]

 [[40 86 76 99 87]
  [82 77 45 24 61]
  [99 90 79 73 95]
  [98 42 53 83 75]]]


In [32]:
product_num = np.array(['A100', 1073, 'AA3R5', 'XP789', '#54X', 1074, '10735P', 'M1-X', 'M2-X', 'M10-X'])

In [34]:
# you can sort numbers and strings in the same list, but will all be treated as
# and sorted as strings

print(np.sort(product_num))

['#54X' '1073' '10735P' '1074' 'A100' 'AA3R5' 'M1-X' 'M10-X' 'M2-X'
 'XP789']


## Filtering on arrays using a condition

In [41]:
# on p 15 in the Student Guide

products_m = product_num['M1-X' in product_num] 
print(products_m)

products_m2 = product_num['M1-X' == product_num] 
print(products_m2)


[['A100' '1073' 'AA3R5' 'XP789' '#54X' '1074' '10735P' 'M1-X' 'M2-X'
  'M10-X']]
['M1-X']


In [39]:
sales_over_50 = sales_figures[sales_figures > 50]
print(sales_over_50)
print(sales_over_50.dtype)

[86 52 58 77 61 57 90 79 73 72 83 75 76 99 82 56 62 72 87 58 99 78 95 98
 53 67]
int32


In [42]:
cond1 = sales_figures <=50

print(sales_figures[cond1])

[ 7 35 16 13  5 37 42 40 40 30 39 34 30  9 16 30 40 48 36 16 38 38 38  9
 33 31 18 45 24 26 17 39 32 39]


## Working with NumPy's Random

In [46]:
# We saw randint() generates random integers

print(np.random.randint(10))

print(np.random.randint(10, 100))

print(np.random.randint(10, 100, size = (2, 5)))

0
38
[[35 94 14 52 51]
 [69 23 91 52 49]]


In [47]:
# rand() is going to generate a random float btwn 0 and 1

print(np.random.rand())

print(np.random.rand(2, 3))

0.8441894045629011
[[0.91607186 0.76368732 0.05535782]
 [0.32865307 0.20655148 0.99455357]]


In [48]:
# NumPy choice() can be used to sample from an array

print(np.random.choice(product_num))

print(np.random.choice(product_num, size = (2, 3)))

M10-X
[['10735P' '1074' '1074']
 ['AA3R5' '1074' 'M2-X']]


In [55]:
pets = ['cat','dog','bunny','snake','fish']

sales_this_week = np.random.choice(pets, p = [.2, .1, .6, 0, .1], size = 10)

print(sales_this_week)

['cat' 'dog' 'bunny' 'bunny' 'bunny' 'bunny' 'bunny' 'bunny' 'dog' 'fish']


# Creating a normal distribution using normal()

In [56]:
x = np.random.normal(loc=5, scale=2, size=(30))

print(x)

[2.8394761  4.96125427 3.24918806 1.69880202 7.03047027 3.17197914
 8.9304028  7.08517887 6.1584747  3.55121211 5.59741992 6.71263289
 5.78784746 3.98454407 3.8764731  3.1635937  2.0126443  5.20028588
 3.71578709 5.00139461 3.44608184 5.86256387 4.74255637 4.72400394
 7.58934777 5.33139309 3.74132012 4.41196646 2.02679611 2.60169219]


In [57]:
y = np.random.normal(loc=5, scale=2, size=(10))
print(y)

[ 3.63039039  5.11102268  4.83376964  7.82380901  2.72784818  2.03122466
 -0.20165897  5.73325735  4.66817462  4.16578914]


In [58]:
# there are other distributions like the Pareto distribution (80, 20) and plenty others

## Manipulating arrays

In [62]:
# shuffle and permutation work similarly
# shuffle is going to reorder the original array (in-place)
# permutation is going to return a new array with values in a shuffled order

grocery_prices = np.array([2.30, 4.99, 3.75, 11.00, 1.99])

print(grocery_prices)

print(np.random.permutation(grocery_prices))

print(grocery_prices)

[ 2.3   4.99  3.75 11.    1.99]
[ 3.75  2.3   4.99  1.99 11.  ]
[ 2.3   4.99  3.75 11.    1.99]


In [64]:
# using shuffle

print(grocery_prices)

print(np.random.shuffle(grocery_prices))  # shuffles the values in place, doesn't return a value

print(grocery_prices)

[11.    4.99  1.99  3.75  2.3 ]
None
[ 1.99  3.75  4.99 11.    2.3 ]


## NumPy ufuncs

In [65]:
# example using plain old multiplication

discount = np.array([.1, .15, .1, .15, .2])

print(grocery_prices * discount)

[0.199  0.5625 0.499  1.65   0.46  ]


In [67]:
print(np.multiply(grocery_prices, discount))  # a lot faster in computer processing

[0.199  0.5625 0.499  1.65   0.46  ]


In [68]:
print(np.add(grocery_prices, grocery_prices))

[ 3.98  7.5   9.98 22.    4.6 ]


In [69]:
print(np.add(grocery_prices, 2))

[ 3.99  5.75  6.99 13.    4.3 ]


In [71]:
new_prices = np.array([1.2, 1.5, 1.9, 2.2, 2.5, 2.9, 3.5, 4.5])

# if halfway between values (e.g. 1.5, 2.5) then NumPy rounds to the nearest EVEN integer

print(np.round(new_prices))

[1. 2. 2. 2. 2. 3. 4. 4.]


In [72]:
# sum() lets you add up the elements in an array

print(np.sum(grocery_prices))

24.03


In [73]:
groc_price_2 = np.array([[2, 3, 4, 5, 10], [6, 7, 2, 1, 4]])

print(groc_price_2)

[[ 2  3  4  5 10]
 [ 6  7  2  1  4]]


In [74]:
print(np.sum(groc_price_2))

44


In [76]:
print(np.sum(groc_price_2, axis = 1))  # sum can work on a specified axis

[24 20]


In [77]:
# cumulative sum provides a rolling total / rolling sum of values

print(np.cumsum(groc_price_2))

[ 2  5  9 14 24 30 37 39 40 44]


In [80]:
# similarly there's prod() to multiply all values in array

print(np.prod(groc_price_2))

403200


In [81]:
print(np.cumprod(groc_price_2))

[     2      6     24    120   1200   7200  50400 100800 100800 403200]


In [82]:
# diff() successive different elements

print(groc_price_2)
print(np.diff(groc_price_2))

[[ 2  3  4  5 10]
 [ 6  7  2  1  4]]
[[ 1  1  1  5]
 [ 1 -5 -1  3]]


In [86]:
print(np.diff(groc_price_2, n=2))

[[ 0  0  4]
 [-6  4  4]]


In [87]:
print(np.diff(groc_price_2, n=3))

[[ 0  4]
 [10  0]]


In [88]:
print(np.diff(groc_price_2, n=4))

[[  4]
 [-10]]


In [ ]:
# another rounding example

for_rounding = np.array([1.5, 2.5, 3.5, 4.5, 5.5])

print(for_rounding)
print(np.round(for_rounding))

[1.5 2.5 3.5 4.5 5.5]
[2. 2. 4. 4. 6.]
